---
plugin: amazon.aws.aws_ec2
regions:
  - eu-north-1
filters:
  instance-state-name: running
  "tag:role": webserver
hostnames:
  - public-ip-address
compose:
  ansible_host: public_ip_address
keyed_groups:
  - key: tags.role

---
plugin: amazon.aws.aws_ec2
regions:
  - eu-north-1
filters:
  instance-state-name: running
  "tag:role": webservers
hostnames:
  - public-ip-address      # Primary hostname will be the public IP
  - tag:Name               # Fall back to Name tag if no public IP
  - dns-name               # Fall back to DNS name
  - private-ip-address     # Last resort, use private IP
keyed_groups:
  - key: tags.role
  - key: tags.Name
    prefix: name
compose:
  ansible_host: public_ip_address
  ansible_user: "'ec2-user'"   # Adjust based on your AMI