---
plugin: amazon.aws.aws_ec2
regions:
  - eu-north-1
filters:
  instance-state-name: running
  "tag:role": webserver
hostnames:
  - public-ip-address      # Primary hostname will be the public IP
keyed_groups:
  - key: tags.role
compose:
  ansible_host: public_ip_address
  ansible_user: "'ec2-user'"   # Adjust based on your AMI
  ansible_ssh_private_key_file: "/home/ec2-user/keys/AnsibleKeyPEM.pem"