---
plugin: amazon.aws.aws_ec2
regions:
  - eu-north-1
filters:
  instance-state-name: running
  "tag:role": webserver
hostnames:
  - public-ip-address
compose:
  ansible_host: public_ip_address
keyed_groups:
  - key: tags.role
